In [1]:
# Load Imports and Libraries
import pandas as pd

In [10]:
# Load in train and test data
train = pd.read_csv("../../data/GiveMeSomeCredit/cs-training.csv")
test = pd.read_csv("../../data/GiveMeSomeCredit/cs-test.csv")

## Training Data

In [11]:
# Get Data Types and null values
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 12 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   Unnamed: 0                            150000 non-null  int64
 1   SeriousDlqin2yrs                      150000 non-null  int64
 2   RevolvingUtilizationOfUnsecuredLines  150000 non-null  float64
 3   age                                   150000 non-null  int64
 4   NumberOfTime30-59DaysPastDueNotWorse  150000 non-null  int64
 5   DebtRatio                             150000 non-null  float64
 6   MonthlyIncome                         120269 non-null  float64
 7   NumberOfOpenCreditLinesAndLoans       150000 non-null  int64
 8   NumberOfTimes90DaysLate               150000 non-null  int64
 9   NumberRealEstateLoansOrLines          150000 non-null  int64
 10  NumberOfTime60-89DaysPastDueNotWorse  150000 non-null  int64
 11  NumberOfDependents                    146076 non-null  float64
dtypes: float64(4), int64(8)
memory usage: 13.7 MB

**Observations**
1. about 30k null vals for Monthly Income
1. about 6k null vals for # of deps
1. All numeric values

**Solutions**
1. impute 'MonthlyIncome'
1. impute 'NumberOfDependents'
1. drop 'Unnamed: 0'

In [19]:
train.drop(columns=['Unnamed: 0'], inplace=True)

In [20]:
# Preview Data
train.head()

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
0,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0
1,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0
2,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0
3,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0
4,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0

In [25]:
train.iloc[: 1:].describe()

,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
count,150000.000000,150000.000000,150000.000000,150000.000000,1.202690e+05,150000.000000,150000.000000,150000.000000,150000.000000,146076.000000
mean,6.048438,52.295207,0.421033,353.005076,6.670221e+03,8.452760,0.265973,1.018240,0.240387,0.757222
std,249.755371,14.771866,4.192781,2037.818523,1.438467e+04,5.145951,4.169304,1.129771,4.155179,1.115086
min,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.029867,41.000000,0.000000,0.175074,3.400000e+03,5.000000,0.000000,0.000000,0.000000,0.000000
50%,0.154181,52.000000,0.000000,0.366508,5.400000e+03,8.000000,0.000000,1.000000,0.000000,0.000000
75%,0.559046,63.000000,0.000000,0.868254,8.249000e+03,11.000000,0.000000,2.000000,0.000000,1.000000
max,50708.000000,109.000000,98.000000,329664.000000,3.008750e+06,58.000000,98.000000,54.000000,98.000000,20.000000

**Observations**
1. 'RevolvingUtilizationOfUnsecuredLines' should be between 0 and 1

**Solution**
1. use top-coding method?

In [15]:
# Refine Target Column with 0 and 1 values
train['SeriousDlqin2yrs'].value_counts()

0    139974
1     10026
Name: SeriousDlqin2yrs, dtype: int64

**Observations**
1. True binary target column
1. imbalanced with more bad borrowers

**Solutions**
1. Research how to handle imbalanced data

## Test Data

In [ ]:
# Get Data Types and null values

In [ ]:
# Preview Data

In [ ]:
# Refine Target Column with 0 and 1 values

## Sample Model Output

In [26]:
# Load Sample Entry data
pd.read_csv("../../data/GiveMeSomeCredit/sampleEntry.csv")

            Id  Probability
0            1     0.080807
1            2     0.040719
2            3     0.011968
3            4     0.067640
4            5     0.108264
...        ...          ...
101498  101499     0.045363
101499  101500     0.343775
101500  101501     0.006970
101501  101502     0.121994
101502  101503     0.044248

[101503 rows x 2 columns]

In [ ]:
def predict_score(array):
    return dict(id, score)